title: 選品智庫：全網優惠速報站
description: 提供蝦皮免運、限時促銷與專業選品建議。
baseurl: "" 
url: "https://lifeexpertise929.github.io"

# 讓 Jekyll 讀取 products 資料夾
collections:
  products:
    output: true
    permalink: /products/:name

# Markdown 設定
markdown: kramdown
highlighter: rouge